# Site settings
title: 'Deepak Puthraya'
description: >
  Deepak Puthraya's Blog.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://deepak.puthraya.com/" # the base hostname & protocol for your site
enforce_ssl: deepak.puthraya.com   # without any protocol
future: true

permalink: /:year/:month/:day/:title:output_ext

collections:
  notes:
    output: true
    permalink: /notes/:path/
  blogs:
    output: true
    permalink: /:path/
  drawings:
    output: true
  links:
    output: true

author:
  fullname: 'Deepak Puthraya'
  github: deepakputhraya
  twitter: deepakputhraya
  linkedin: https://www.linkedin.com/in/deepakputhraya

# Syntax highlighting
highlightstyle: 'atelier-sulphurpool.light'
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]

# Handling Reading
exclude: ["README.md", "README.html", "node_modules", "gulpfile.js"]

# Build settings
highlighter: null
markdown: kramdown

social:
  name: Deepak Puthraya
  links:
    - https://twitter.com/deepakputhraya
    - https://www.google.com/+deepakputhraya
    - https://github.com/deepakputhraya
    - https://www.linkedin.com/in/deepakputhraya

plugins:
  - jekyll-seo-tag

